title: Marlon Zabala # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C4D03AQHwI7K30XiwQg/profile-displayphoto-shrink_200_200/0?e=1597276800&v=beta&t=UNLTFZhPviGlFKoUdGljbxhXTdjvZbZN0rap-n-GClw" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm an Android Developer
  <br><br>
  I have made many apps
  <br>
  Here is my portfolio website
  <br><br>
  <a href="https://www.linkedin.com/in/marlonzabala/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
